export const VENEZUELA_BANKS = [
    { code: '0156', name: '100% BANCO' },
    { code: '0196', name: 'ABN AMRO BANK' },
    { code: '0172', name: 'BANCAMIGA BANCO MICROFINANCIERO, C.A.' },
    { code: '0171', name: 'BANCO ACTIVO BANCO COMERCIAL, C.A.' },
    { code: '0166', name: 'BANCO AGRICOLA' },
    { code: '0175', name: 'BANCO BICENTENARIO' },
    { code: '0128', name: 'BANCO CARONI, C.A. BANCO UNIVERSAL' },
    { code: '0164', name: 'BANCO DE DESARROLLO DEL MICROEMPRESARIO' },
    { code: '0102', name: 'BANCO DE VENEZUELA S.A.I.C.A.' },
    { code: '0114', name: 'BANCO DEL CARIBE C.A.' },
    { code: '0149', name: 'BANCO DEL PUEBLO SOBERANO C.A.' },
    { code: '0163', name: 'BANCO DEL TESORO' },
    { code: '0176', name: 'BANCO ESPIRITO SANTO, S.A.' },
    { code: '0115', name: 'BANCO EXTERIOR C.A.' },
    { code: '0003', name: 'BANCO INDUSTRIAL DE VENEZUELA.' },
    { code: '0173', name: 'BANCO INTERNACIONAL DE DESARROLLO, C.A.' },
    { code: '0105', name: 'BANCO MERCANTIL C.A.' },
    { code: '0191', name: 'BANCO NACIONAL DE CREDITO' },
    { code: '0116', name: 'BANCO OCCIDENTAL DE DESCUENTO.' },
    { code: '0138', name: 'BANCO PLAZA' },
    { code: '0108', name: 'BANCO PROVINCIAL BBVA' },
    { code: '0104', name: 'BANCO VENEZOLANO DE CREDITO S.A.' },
    { code: '0168', name: 'BANCRECER S.A. BANCO DE DESARROLLO' },
    { code: '0134', name: 'BANESCO BANCO UNIVERSAL' },
    { code: '0177', name: 'BANFANB' },
    { code: '0146', name: 'BANGENTE' },
    { code: '0174', name: 'BANPLUS BANCO COMERCIAL C.A' },
    { code: '0190', name: 'CITIBANK.' },
    { code: '0121', name: 'CORP BANCA.' },
    { code: '0157', name: 'DELSUR BANCO UNIVERSAL' },
    { code: '0151', name: 'FONDO COMUN' },
    { code: '0601', name: 'INSTITUTO MUNICIPAL DE CRÉDITO POPULAR' },
    { code: '0169', name: 'MIBANCO BANCO DE DESARROLLO, C.A.' },
    { code: '0137', name: 'SOFITASA' }
];
